#!/bin/sh
cat <<EOF
🐱 CAT FACE
😸 GRINNING CAT FACE WITH SMILING EYES
😹 CAT FACE WITH TEARS OF JOY
😺 SMILING CAT FACE WITH OPEN MOUTH
😻 SMILING CAT FACE WITH HEART-SHAPED EYES
😼 CAT FACE WITH WRY SMILE
😽 KISSING CAT FACE WITH CLOSED EYES
😾 POUTING CAT FACE
😿 CRYING CAT FACE
🙀 WEARY CAT FACE
EOF
